name: help me understand why
favicon: null
layout_spectrum: 0.31152641330845654
typography_spectrum: 0.783511406974867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7403686081524938
  lightness: 0.842258426360786
  saturation: 0.05481359548866749
  rhythmicContrast: 0.4482778685633093
purpose: []
